// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Cancel() {
  return window['go']['app']['api']['Cancel']();
}

export function CloseSend() {
  return window['go']['app']['api']['CloseSend']();
}

export function Connect(arg1, arg2, arg3) {
  return window['go']['app']['api']['Connect'](arg1, arg2, arg3);
}

export function DeleteWorkspace(arg1) {
  return window['go']['app']['api']['DeleteWorkspace'](arg1);
}

export function ExportCommands(arg1, arg2, arg3) {
  return window['go']['app']['api']['ExportCommands'](arg1, arg2, arg3);
}

export function FindProtoFiles() {
  return window['go']['app']['api']['FindProtoFiles']();
}

export function GetMetadata(arg1) {
  return window['go']['app']['api']['GetMetadata'](arg1);
}

export function GetRawMessageState(arg1) {
  return window['go']['app']['api']['GetRawMessageState'](arg1);
}

export function GetReflectMetadata(arg1) {
  return window['go']['app']['api']['GetReflectMetadata'](arg1);
}

export function GetWorkspaceOptions() {
  return window['go']['app']['api']['GetWorkspaceOptions']();
}

export function ImportCommand(arg1, arg2) {
  return window['go']['app']['api']['ImportCommand'](arg1, arg2);
}

export function ListWorkspaces() {
  return window['go']['app']['api']['ListWorkspaces']();
}

export function RetryConnection() {
  return window['go']['app']['api']['RetryConnection']();
}

export function SelectDirectory() {
  return window['go']['app']['api']['SelectDirectory']();
}

export function SelectMethod(arg1, arg2, arg3) {
  return window['go']['app']['api']['SelectMethod'](arg1, arg2, arg3);
}

export function SelectWorkspace(arg1) {
  return window['go']['app']['api']['SelectWorkspace'](arg1);
}

export function Send(arg1, arg2, arg3) {
  return window['go']['app']['api']['Send'](arg1, arg2, arg3);
}

export function WailsInit(arg1) {
  return window['go']['app']['api']['WailsInit'](arg1);
}

export function WailsShutdown() {
  return window['go']['app']['api']['WailsShutdown']();
}
